version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: phpstan/phpstan
    versions:
    - 0.12.70
    - 0.12.71
    - 0.12.74
    - 0.12.77
    - 0.12.78
    - 0.12.79
    - 0.12.80
    - 0.12.81
    - 0.12.82
    - 0.12.83
    - 0.12.84
  - dependency-name: vimeo/psalm
    versions:
    - 4.4.1
    - 4.5.0
    - 4.5.1
    - 4.6.0
    - 4.6.1
    - 4.6.2
    - 4.6.3
    - 4.6.4
    - 4.7.0
  - dependency-name: symfony/form
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
    - 5.2.5
  - dependency-name: symfony/string
    versions:
    - 5.2.1
    - 5.2.2
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/browser-kit
    versions:
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/dotenv
    versions:
    - 5.2.1
    - 5.2.3
