sudo: required

env:
  global:
    - RUN_SONAR_SCANNER=0

language: php

services:
    - docker

addons:
  sonarcloud:
    organization: "pmononoke"
    token:
      secure: "7a509e4bf334ca44fd697d725c627ba40fea6a77"

matrix:
    fast_finish: true
    include:
        - php: 7.2
          env: RUN_SONAR_SCANNER=1
        - php: 7.3
        - php: 7.4snapshot


cache:
  directories:
  - $HOME/.composer/cache

.steps:
  #
  #   CI STEP
  #
  - &add-composer-bin-dir-to-path |
      export PATH="$PATH:$HOME/.composer/vendor/bin"

  - &disable-xdebug-php-extension |
      phpenv config-rm xdebug.ini || echo "xdebug not available"

  - &disable-php-memory-limit |
      echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  - &app-clear-test-cache |
      bin/console cache:clear -e test

  - &app-database-schema-update |
      bin/console doctrine:schema:update --force --no-interaction -e test

  - &run-phpunit-tests |
      bin/phpunit --colors=always --coverage-clover=coverage-report.clover --log-junit=test-report.xml

  - &run-phpstan-tests |
      vendor/bin/phpstan analyse

before_install:
  - cp ci/.env.test.travis .env.test

install:
  - docker-compose -f tests/docker/docker-compose.yml up -d
  - composer install
  - ./bin/phpunit install

before_script:

  - *app-clear-test-cache

  - *app-database-schema-update


script:
  - *run-phpstan-tests
  - *run-phpunit-tests

after_success:
  - if [[ $RUN_SONAR_SCANNER == "1" ]]; then sonar-scanner -Dproject.settings=sonar-project.properties -Dsonar.projectVersion=$TRAVIS_TAG; fi

