<?php

namespace App\Tests\Functional;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class SecurityControllerTest extends WebTestCase
{
    //private $client = null;

    protected function setUp():void
    {
        $this->markTestIncomplete();

        //parent::setUp();
        //self::bootKernel();
        //$kernel = static::bootKernel();
        //$this->client = static::createClient();
    }

    /**
     * @test
     * @dataProvider getBackEndUrls
     */
    public function protect_backend_from_anonymus_users_redirect_to_login(string $httpMethod, string $url): void
    {
        $client = static::createClient();

        //$client = $this->createClient();//  static::createClient();
        $client->request($httpMethod, $url);

        $this->assertTrue($client->getResponse()->isRedirect());
        $crawler = $client->followRedirect();
        $this->assertTrue($crawler->filter('html:contains("Login")')->count() > 0);
    }

//    public function getUrlsForAnonymusUsers()
//    {
//        yield ['GET', '/admin/patient/'];
//    }
//

    /**
     * @return \Generator<array>
     */
    public function getBackEndUrls(): \Generator
    {
        yield ['GET', '/admin/patient/'];
    }

//    public function testShowPost()
//    {
//        $client = static::createClient([],[]);
//
//        $this->client->request('GET', '/');
//
//        $this->client->assertEquals(200, $this->client->getResponse()->getStatusCode());
//    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        //$this->client = null;
        //$this->ensureKernelShutdown();
    }
}
